### PR TITLE
Fix/angular 14

### PR DESCRIPTION
**Pull request by nerumo**
## PR Checklist

Please check if your PR fulfills the following requirements:

- [X] The commit message follows our guidelines: https://github.com/datorama/akita/blob/master/CONTRIBUTING.md#commit
- [] Tests for the changes have been added (for bug fixes / features)
- [] Docs have been added / updated (for bug fixes / features)

## PR Type

What kind of change does this PR introduce?

```
[X] Bugfix
[ ] Feature
[ ] Code style update (formatting, local variables)
[ ] Refactoring (no functional changes, no api changes)
[ ] Build related changes
[ ] CI related changes
[ ] Documentation content changes
[ ] Other... Please describe:
```

## What is the current behavior?
Akita is incompatibility with the last Typescript version, 4.8, used on NX and Angular 14 by default.

Issue Number: #870

## What is the new behavior?
Akita can be used on typescript 4.8

## Does this PR introduce a breaking change?

```
[ ] Yes
[X] No
```

## Other information
NX workspace had to be updated, it changes somes config file slightly.

### CODE REVIEW

**Comment by nerumo** [comment]
image

what's going with the salesforce CLA?

**Comment by corsairdnb** [comment]
@NetanelBasal Could you please pay attention to this PR?
The [issue](https://github.com/salesforce/akita/issues/870) prevents us from using Akita with latest Typescript and Angular versions, so it's crucial to be fixed ASAP.
Thank you!

**Comment by masatada-kurihara** [comment]
@salesforce-datorama-checkmarx 
This package that your company manage is in a poor state of maintenance, leaving vulnerabilities in the dependencies package, not keeping up with the latest version of Angular, and not being appropriate as OSS.
Please review your management system.

https://github.com/salesforce/akita/pull/1037

**Comment by corsairdnb** [comment]
@jimjag Thank you for merging this! How can we get the new version released on npm?

**Comment by arizmendiomar** [comment]
Any news about a new release?
Does someone knows to whom do we need to reach out to get a new release?

**Pull request merged**
