### PR TITLE
Linting libraries phase 1 - continued

### PR DESCRIPTION
**Pull request by snebjorn**
## PR Checklist

Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/datorama/akita/blob/master/CONTRIBUTING.md#commit
- [x] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type

What kind of change does this PR introduce?

```
[ ] Bugfix
[ ] Feature
[x] Code style update (formatting, local variables)
[x] Refactoring (no functional changes, no api changes)
[ ] Build related changes
[x] CI related changes
[ ] Documentation content changes
[ ] Other... Please describe:
```

## Does this PR introduce a breaking change?

```
[ ] Yes
[x] No
```

## Additional info

Part of #401

### CODE REVIEW

**Comment by snebjorn** [comment]
@NetanelBasal have you had some time to look at this? Can I help somehow?

**Comment by NetanelBasal** [comment]
Hi, I'm not sure what's the status here?

**Comment by snebjorn** [comment]
I updated it with master (at the time) and fixed the remaining linting rules (and relaxed them a bit)

The changes shouldn't change how any business rules and only be formatting/flavor changes

**Comment by NetanelBasal** [comment]
Ok, I'll go over it later on. Thanks

**Pull request closed without merging**
